# image:
#   repository: oryd/oathkeeper
#   tag: v0.40.0
# sidecar:
#   image:
#     repository: oryd/oathkeeper-maester
#     tag: v0.1.7
maester:
  enabled: false
  nameOverride: trace-shield-oathkeeper-maester
deployment:
  automountServiceAccountToken: true
oathkeeper:
  mutatorIdTokenJWKs: |
    {
      "keys": [
        {
          "use": "sig",
          "kty": "RSA",
          "kid": "a2aa9739-d753-4a0d-87ee-61f101050277",
          "alg": "RS256",
          "n": "zpjSl0ySsdk_YC4ZJYYV-cSznWkzndTo0lyvkYmeBkW60YHuHzXaviHqonY_DjFBdnZC0Vs_QTWmBlZvPzTp4Oni-eOetP-Ce3-B8jkGWpKFOjTLw7uwR3b3jm_mFNiz1dV_utWiweqx62Se0SyYaAXrgStU8-3P2Us7_kz5NnBVL1E7aEP40aB7nytLvPhXau-YhFmUfgykAcov0QrnNY0DH0eTcwL19UysvlKx6Uiu6mnbaFE1qx8X2m2xuLpErfiqj6wLCdCYMWdRTHiVsQMtTzSwuPuXfH7J06GTo3I1cEWN8Mb-RJxlosJA_q7hEd43yYisCO-8szX0lgCasw",
          "e": "AQAB",
          "d": "x3dfY_rna1UQTmFToBoMn6Edte47irhkra4VSNPwwaeTTvI-oN2TO51td7vo91_xD1nw-0c5FFGi4V2UfRcudBv9LD1rHt_O8EPUh7QtAUeT3_XXgjx1Xxpqu5goMZpkTyGZ-B6JzOY3L8lvWQ_Qeia1EXpvxC-oTOjJnKZeuwIPlcoNKMRU-mIYOnkRFfnUvrDm7N9UZEp3PfI3vhE9AquP1PEvz5KTUYkubsfmupqqR6FmMUm6ulGT7guhBw9A3vxIYbYGKvXLdBvn68mENrEYxXrwmu6ITMh_y208M5rC-hgEHIAIvMu1aVW6jNgyQTunsGST3UyrSbwjI0K9UQ",
          "p": "77fDvnfHRFEgyi7mh0c6fAdtMEMJ05W8NwTG_D-cSwfWipfTwJJrroWoRwEgdAg5AWGq-MNUzrubTVXoJdC2T4g1o-VRZkKKYoMvav3CvOIMzCBxBs9I_GAKr5NCSk7maksMqiCTMhmkoZ5RPuMYMY_YzxKNAbjBd9qFLfaVAqs",
          "q": "3KEmPA2XQkf7dvtpY1Xkp1IfMV_UBdmYk7J6dB5BYqzviQWdEFvWaSATJ_7qV1dw0JDZynOgipp8gvoL-RepfjtArhPz41wB3J2xmBYrBr1sJ-x5eqAvMkQk2bd5KTor44e79TRIkmkFYAIdUQ5JdVXPA13S8WUZfb_bAbwaCBk",
          "dp": "5uyy32AJkNFKchqeLsE6INMSp0RdSftbtfCfM86fZFQno5lA_qjOnO_avJPkTILDT4ZjqoKYxxJJOEXCffNCPPltGvbE5GrDXsUbP8k2-LgWNeoml7XFjIGEqcCFQoohQ1IK4DTDN6cmRh76C0e_Pbdh15D6TydJEIlsdGuu_kM",
          "dq": "aegFNYCEojFxeTzX6vIZL2RRSt8oJKK-Be__reu0EUzYMtr5-RdMhev6phFMph54LfXKRc9ZOg9MQ4cJ5klAeDKzKpyzTukkj6U20b2aa8LTvxpZec6YuTVSxxu2Ul71IGRQijTNvVIiXWLGddk409Ub6Q7JqkyQfvdwhpWnnUk",
          "qi": "P68-EwgcRy9ce_PZ75c909cU7dzCiaGcTX1psJiXmQAFBcG0msWfsyHGbllOZG27pKde78ORGJDYDNk1FqTwsogZyCP87EiBmOoqXWnMvKYfJ1DOx7x42LMAGwMD3bgQj9jgRACxFJG4n3NI6uFlFruyl_CLQzwW_rQFHshLK7Q"
        }
      ]
    }
  managedAccessRules: true
  config:
    log:
      level: debug
    serve:
      proxy:
        tls:
          cert:
            base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuRENDQW9TZ0F3SUJBZ0lVQUt2WldDL25lR0thTU02M3NnQkxJblo0alNzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xXVzkxY2tOdmJYQmhibmt3SGhjTk1qUXdNVE13TVRVME5EVXpXaGNOTWpZeApNREkyTVRVME5EVXpXakFXTVJRd0VnWURWUVFEREF0WmIzVnlRMjl0Y0dGdWVUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKL3RXenJsUTAveHlTZFU0dm5aY3plVko5OEdWb2xhT2MzMGdhQWMKY3lrdmpIcTVmTXozWXJyam45bWlvNFo1N2tUSHB6elBEdTc5ZnZZTU85c1drc2hyQWpaUlU2TEVTeGh0RHNiNQo3UDNNcm9CRm9Wc2xqZGJUMDB0ckpranNPeXl5Vk9vOEY1QUlJR3pxQjI2MENObU9MaTNiaVRSMGJwYjhscmdZClZQZTBUYjBlM2YvcTR1WTdnc09UMkJHL2RzcnpqWlVScEtJUS9LbThjYzJyc292azMvelJ2THI4Qm95Mm5qNXIKODdqaUltTE9JV2FMbmVabDhjaEN3dnRvZDc4N0tUQy9LcklPR0RKclpESXh3dm9ocFVvU3NCaWRoczlxSGVrMwpFODZIVUZVREhaZjZsR2lGcDBkZVpzU3lFRHB1dElLNXJKOGJNSEZvSlVqMGFSVUNBd0VBQWFPQjRUQ0IzakFSCkJnbGdoa2dCaHZoQ0FRRUVCQU1DQmtBd0N3WURWUjBQQkFRREFnWGdNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUYKQndNQk1CMEdBMVVkRGdRV0JCUVNpL0VUQkduNkdYd2UwSFZ2R2lTNGQyV2hWakFmQmdOVkhTTUVHREFXZ0JRagpqMXk1VXBYd3ROTWM2UU5aV0g4RTR0TzRhekJuQmdOVkhSRUVZREJlZ2hoc2IyTmhiR2h2YzNRdWRISmhZMlZ6CmFHbGxiR1F1YVcrQ0dpb3ViRzlqWVd4b2IzTjBMblJ5WVdObGMyaHBaV3hrTG1sdmdnbHNiMk5oYkdodmMzU0MKQ3lvdWJHOWpZV3hvYjNOMGdna3hNamN1TUM0d0xqR0NBem82TVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQQpBVGdWbGdVaWNUY2VUQS9DMG9MdzFITCtmN1NDS2ZxTlY4aDQrVENTRDZZWXZkQ0Q3dFdxQjF4VHE1dXNzazZ1CnVnWlEzbTNNYVVOMkZCOGdDQjE0STZySC9uMDdycEdwZ29zQ3BDYlRHSGY4cHJBRmxINVdXNEI2allGUzIvUTUKaVpHbEM5TmtueGQrekM2eDFtdUt3T2JWbTE1SGFKK1JsUjVNaHNBam1VeUxDcmZLc1dHZDhwYmVpeEduSmkraQo3MCtKaG5aN1RUeXMybHhwUG5zQnJUNDNVWDdqTm9xVGtWM0NzQUJwWTlYQ1ZDL2VMd0hHZm1ONzdaNnJXZmZqCnFuMXh0SVN4RzkvZmpXemZhVFVnTitOc01TOGdnTklpeDNoUFlmT3VKKzFzSjJaRm5LUXhwcHJGckh0VEl0d3UKZjFmTDlXNGJNblJUWXo0Y0xSbHpmcWxYNFhwVUYxV2xWaUErVFJhYWJCeFlVeENFR1BuWG82V1FwUGFhWjlaQgowR2sxR0MxWlJKWFFlekUxelRVT2pxd2w3T1g2WHN1OEZvcnA5SHFVdVFtRXZyc2VaVHcxbzI2MlptK09nTysrCmxMeVpuL2M2UUhOUGRKcjBOUEhYNTkwYU0zN3hHWlVvd0kwOUZmQktsN2IrY1VXeUVDTXRIRTNZZnVFRmFyVWcKVUc0VG9DQ0YxaDVQZFdReStoZkdRL1ltdVEwZjQyQjdBL0ZRUW1tNXdHRGlmb1dPOUFnd1dsYWlqWnBVd2p6VAp2L1dqNFZhcFdlTUZBUXdnTURXYVAzWXdnOWF1T3FCOG9UNFcwRVFEZnV5Q2N4ajgrM1F0VjM4bHFrdGtlK2wwClJ6VFZOdWQxcUpYOE1oWHoxcGRqdCtqUm5vM0tGam9SeUtLR2U5UitWQkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          key:
            base64: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ2Y3VnM2NVVOUDhja24KVk9MNTJYTTNsU2ZmQmxhSldqbk45SUdnSEhNcEw0eDZ1WHpNOTJLNjQ1L1pvcU9HZWU1RXg2Yzh6dzd1L1g3MgpERHZiRnBMSWF3STJVVk9peEVzWWJRN0crZXo5eks2QVJhRmJKWTNXMDlOTGF5Wkk3RHNzc2xUcVBCZVFDQ0JzCjZnZHV0QWpaamk0dDI0azBkRzZXL0phNEdGVDN0RTI5SHQzLzZ1TG1PNExEazlnUnYzYks4NDJWRWFTaUVQeXAKdkhITnE3S0w1Ti84MGJ5Ni9BYU10cDQrYS9PNDRpSml6aUZtaTUzbVpmSElRc0w3YUhlL095a3d2eXF5RGhneQphMlF5TWNMNklhVktFckFZblliUGFoM3BOeFBPaDFCVkF4MlgrcFJvaGFkSFhtYkVzaEE2YnJTQ3VheWZHekJ4CmFDVkk5R2tWQWdNQkFBRUNnZ0VBQjNUa3JRdjYwSGtWM095YlRKK2VrZmZnRFFrRVNKRXV1QjN2Vy9kczh5aFIKWk00ak5kZFBBTkcrSnBmcnNmTWJjSlRkTDZaT2dad2cxYU5mdUdrR3NsWXk4SW9TMitMMUhCQWNWcHRaT1JndApzVjROd095R1ZDbVBqMzVSSWFpZllGMGhrbTVNMXZLdll3U2laaFNrMlAxRkdwbVlLSEdlcFJHUDRYT0RwVmVZCkxMWFd6ZklvN3puS3JoaHFEbGNHbnUwclBPN1NIMHhibWRLS1pUYUlsRjZOZnZuZDFEeUEvWmRGOGltWFJLamkKZnVPc2tPL2pYU08xNWRQMSswTWcrUjRvcm94bzR6aC90N3Y1NmY0bXNkYWtFWm5pZnF3Y3VIZXhhamswdWZVSQplVjRCckR6dXlaMmFVNnM1RUZyNjlPQ0g4NzN2b1NQMXZUcDlQNGNxNFFLQmdRRGU0ZkJCVHBkdk9GbkxkcU5QCjN3ZElCc2JpemkyenRWNEMwVksvVS9tdllhb1E4aFNRWDZGQVRZSFlXTGlpd2VZV3JjRkhOaVF2ekJxckluVU8KMEpJQkExUFl3bHhGWDRhK2VCRG5PWkFFWEdxV0RLQTJiUFlzM3U1U3NidWtLbXprZktzYkMrSGthWGRIWUNlYwpjb0FOd2JhaTRJdmtVT1BkV1ZXV0dUbElDUUtCZ1FDM3NMU0ExeHo2VHEwVk9kdW9qcXg4SUVQVkJWUWR3NktlCm40UG0xRzhJM3J2bEs4MGJpV0NKUDMzQlZqTERlQ2lhWDV3TVEvaGV2YTh4YUJJSEFYOWwzN0dvSGNGcTVZNVcKVkU4REUyRTBqSzRNRUdmd1pPdm53WmF5VjJmZExwd1RIaVduMG9EdkhwdW9pMmI4U2Q2ZnB3a25NcGhLUFhCYwpMcVZNdjVtanJRS0JnRk1xTDBIUEY0WnltbDduSjh6M3hYbkV2WldIcFZuM0JOczhUQW9FUlppQmNybmIrbnhjCmtvaXg0dzlkRzVmdmpmRk1hR0F2L1pTd0xndEpVakJ5OXVmVjNBVjNrSUo2UUliMXVpanRPNlhFN2lpTEVZVDkKWjJZYTBRYWVOd3Zzb0xFcEs1ZHQrWjRIRkhEWG1qQXdNVVB3MGpzNFdqcVpURTBkdG1mSmhhd3hBb0dCQUxJeApvV2s3Uk1rdGVZcVZ6aGorRHlWNngxTG5FR3F2VmhvNjlHSUF3cFlBUEpaY24yU1BLQzc4Z0tvRlRNbUN6eUN5CmoxYjJ1UUp2VUh6RlVIZXJaRU1YZGVoNHRTRlYvM2FQNHZaQTNwTnp4WU8raHBZVjBTUEtFTDZCUENpOUJuc2wKUzdJNTZ3b016MFA1dDdZV2t2aWR1YXRrMFlkemdvUnFXOERRUGVNaEFvR0JBSUE5eC9QZjFWZXFxMEF5MmwycApyaWdmWlZ4S2dzMVRsMm5ncDh6WVk4RFRveThBRDBaSyt2dlBUandyQW05bTVkTEJlM3RTcEN6T1NnbXBGTHpQCnN0eWdpc1ZKam10TVBUMTU5Ti91K01XZ0MwVVNTWUw3cEE1czR4NUtZT0haVUJiMFhYUWxkVUZCR2NTNFpkLzIKUTZ4WXFqQTFxNXRNc0NJTFV5VUlLb2YrCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
        port: 4455
    access_rules:
      matching_strategy: regexp
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest

      cookie_session:
        enabled: true
        config:
          check_session_url: http://kratos-public.kratos/sessions/whoami
          preserve_path: true
          extra_from: "@this"
          subject_from: "identity.id"
          only:
            - ory_kratos_session

      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin.hydra:4445/admin/oauth2/introspect
          # scope_strategy: exact

      noop:
        enabled: true

    authorizers:
      allow:
        enabled: true
      # remote_json:
      #   enabled: true
      #   config:
      #     remote: http://kubricks-keto-read/relation-tuples/check
      #     payload: |
      #       {
      #         "subject": "{{ print .Subject }}",
      #         "resource": "{{ printIndex .MatchContext.RegexpCaptureGroups 0 }}"
      #       }
    mutators:
      noop:
        enabled: true

      id_token:
        enabled: true
        config:
          issuer_url: https://localhost.traceshield.io:4455/
          jwks_url: file:///etc/secrets/mutator.id_token.jwks.json
          claims: |
            {
              "session": {{ .Extra | toJson }}
            }
      header:
        enabled: true
        config:
          headers: {}
      hydrator:
        enabled: true
        config:
          api:
            url: http://temp-go-mimir/
    errors:
      fallback:
        - json
      handlers:
        redirect:
          enabled: true
          config:
            to: https://localhost.traceshield.io/login
            when:
              - error:
                  - unauthorized
                  - forbidden
                request:
                  header:
                    accept:
                      # We don't want this for application/json requests, only browser requests!
                      - text/html
        json:
          enabled: true
          config:
            verbose: true

ingress:
  proxy:
    enabled: false
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: kratos.mimir-cloud.traceshield.io
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: mimir.mimir-cloud.traceshield.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - kratos.mimir-cloud.traceshield.io
          - mimir.mimir-cloud.traceshield.io
        secretName: kubricks-oathkeeper-proxy-tls
