- id: frontend:public
  upstream:
    url: http://frontend.default.svc.cluster.local
    preserve_host: true
  match:
    url: <http|https>://localhost.traceshield.io:4455</|/registration.*|/welcome.*|/recovery.*|/verification.*|/login.*|/consent.*|/error|/404|/500|/.*.css|./*.js|/.*.png|/.*.svg|/assets/.*|/static/.*|/users|/groups|/settings.*|/.*.json>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: api-server:graphiql:public
  upstream:
    url: http://api-server.default.svc.cluster.local:8082
    preserve_host: true
  match:
    url: <http|https>://localhost.traceshield.io:4455/graphiql
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: api-server:graphql:public
  upstream:
    url: http://api-server.default.svc.cluster.local:8082
    preserve_host: true
  match:
    url: <http|https>://localhost.traceshield.io:4455/graphql
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: api-server:user-webhok:public
  upstream:
    url: http://api-server.default.svc.cluster.local:8082
    preserve_host: true
  match:
    url: <http|https>://localhost.traceshield.io:4455/user-webhook
    methods:
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: api-server:consent:public
  upstream:
    url: http://api-server.default.svc.cluster.local:8082
    preserve_host: true
  match:
    url: <http|https>://localhost.traceshield.io:4455/oauth2/consent
    methods:
      - POST
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: ory:kratos:public
  upstream:
    url: http://kratos-public.kratos
    strip_path: /.ory/kratos/public
    preserve_host: true
  match:
    url: <http|https>://localhost.traceshield.io:4455/.ory/kratos/public/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: ory:hydra:public
  upstream:
    url: http://hydra-public.hydra:4444
    preserve_host: true
  match:
    url: <http|https>://hydra.localhost.traceshield.io:4455<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: grafana:grafana:public
  upstream:
    url: http://grafana.grafana:80
    preserve_host: true
  match:
    url: <http|https>://grafana.localhost.traceshield.io:4455<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
- id: grafana:mimir:read_metrics
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - GET
      - POST
    url: <http|https>://mimir.localhost.traceshield.io:4455/prometheus/api/v1/<status|query|query_range|query_exemplars|series|label|metadata|read|cardinality><.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "read_metrics",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:write_metrics
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - POST
    url: <http|https>://mimir.localhost.traceshield.io:4455</api/v1/push.*|/otlp/v1/metrics.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "write_metrics",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:read_metrics_rules
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - GET
    url: <http|https>://mimir.localhost.traceshield.io:4455</ruler/rule_groups.*|/prometheus/api/v1/rules.*|/prometheus/api/v1/alerts.*|/prometheus/config/v1/rules.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "read_metrics_rules",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:write_metrics_rules
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - POST
    url: <http|https>://mimir.localhost.traceshield.io:4455/prometheus/config/v1/rules/<.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "write_metrics_rules",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:delete_metrics_rules
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - DELETE
    url: <http|https>://mimir.localhost.traceshield.io:4455/prometheus/config/v1/rules/<.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "delete_metrics_rules",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:read_metrics_alerts
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - GET
    url: <http|https>://mimir.localhost.traceshield.io:4455</multitenant_alertmanager/configs.*|/api/v1/alerts.*> #TODO: add /alertmanager
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "read_metrics_alerts",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:write_metrics_alerts
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - POST
    url: <http|https>://mimir.localhost.traceshield.io:4455/api/v1/alerts<.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "write_metrics_alerts",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir:delete_metrics_alerts
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - DELETE
    url: <http|https>://mimir.localhost.traceshield.io:4455/api/v1/alerts<.*>
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
  authorizer:
    handler: remote_json
    config:
      remote: http://api-server.default.svc.cluster.local:8082/check
      forward_response_headers_to_upstream:
      - X-Scope-OrgID
      payload: |
        {
          "subject": {{`"{{ print .Subject }}"`}},
          "requestedPermission": "delete_metrics_alerts",
          "isOAuth2Client": {{`{{ or (eq (print .Subject) (print .Extra.client_id)) (eq (print .Subject) (regexReplaceAll ":.*" (.MatchContext.Header.Get "Authorization" | trimPrefix "Basic " | b64dec) "")) }}`}}
        }
  mutators:
    - handler: noop
- id: grafana:mimir-alertmanager:protected
  upstream:
    url: http://mimir-nginx.mimir.svc.cluster.local
    preserve_host: true
  match:
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    url: <http|https>://mimir.localhost.traceshield.io:4455/alertmanager<.*> # TODO: does this need to be separate
  authenticators:
    - handler: oauth2_introspection
    - handler: oauth2_client_credentials
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: hydrator
      config:
        api:
          url: http://api-server.default.svc.cluster.local:8082/tenant-hydrator
# - id: ory:kratos-selfservice-ui-node:anonymous
#   upstream:
#     url: http://oauth-stack-kratos-selfservice-ui-node # TODO: use proper templating
#     preserve_host: true
#   match:
#     methods:
#       - GET
#       - POST # needed for consent
#     # TODO: cleanup templating
#     url: https://kratos.mimir-cloud.traceshield.io<{/,/registration,/welcome,/recovery,/verification,/login,/consent,/error,/404,/500,/**.css,/**.js,/**.png,/**.svg,/assets/**}>
#   authenticators:
#     - handler: noop
#   authorizer:
#     handler: allow
#   mutators:
#     - handler: noop
#       config: {}
# - id: ory:kratos-selfservice-ui-node:protected
#   upstream:
#     url: http://oauth-stack-kratos-selfservice-ui-node # TODO: use proper templating
#     preserve_host: true
#   match:
#     methods:
#       - GET
#     # TODO: cleanup templating
#     url: https://kratos.mimir-cloud.traceshield.io/<{debug,dashboard,settings,sessions}{/,}>
#   authenticators:
#     - handler: cookie_session
#   authorizer:
#     handler: allow
#   mutators:
#     - handler: id_token
#   errors:
#     - handler: redirect
#       config:
#         to: https://kratos.mimir-cloud.traceshield.io/login
# - id: grafana:mimir-api:protected
#   upstream:
#     url: http://mimir-nginx.mimir # TODO: use proper templating
#     preserve_host: true
#   match:
#     methods:
#       - GET
#       - POST
#       - PUT
#       - DELETE
#       - PATCH
#       - OPTIONS
#     # TODO: cleanup templating
#     url: https://mimir.mimir-cloud.traceshield.io/api<**>
#   authenticators:
#     - handler: oauth2_introspection
#       # config:
#       #   required_scope:
#       #     - grafana:read
#       #     - grafana:write
#   authorizer:
#     handler: allow
#   mutators:
#     - handler: header
#       config:
#         headers:
#           X-Scope-OrgID: mimir-cloud-oauth2
# - id: grafana:mimir-prometheus:protected
#   upstream:
#     url: http://mimir-nginx.mimir # TODO: use proper templating
#     preserve_host: true
#   match:
#     methods:
#       - GET
#       - POST
#       - PUT
#       - DELETE
#       - PATCH
#       - OPTIONS
#     # TODO: cleanup templating
#     url: https://mimir.mimir-cloud.traceshield.io/prometheus<**>
#   authenticators:
#     - handler: oauth2_introspection
#       # config:
#       #   required_scope:
#       #     - grafana:read
#       #     - grafana:write
#   authorizer:
#     handler: allow
#   mutators:
#     - handler: header
#       config:
#         headers:
#           X-Scope-OrgID: mimir-cloud|mimir-cloud-2|mimir-cloud-oauth2
#   errors:
#     - handler: redirect
#       config:
#         to: https://kratos.mimir-cloud.traceshield.io/login
